site_name: Humblebee AI - Blog
site_description: 'This repository is for "blog.humblebee.ai" technical blog.'
site_url: https://blog.humblebee.ai
repo_name: humblebeeintel/docs.humblebee-blog
repo_url: https://github.com/humblebeeintel/docs.humblebee-blog
theme:
  name: material
  # name: readthedocs
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    # logo: fontawesome/brands/python
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/tex-mml-chtml.js
plugins:
  - meta
  - tags
  - search
  - awesome-nav
  # - mkdocstrings
  - redirects:
      redirect_maps:
        index.md: blog/index.md
  - blog:
      post_excerpt: required
      post_excerpt_max_authors: 3
      post_date_format: medium
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      blog_toc: true
      draft: true
      draft_if_future_date: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      # categories_allowed:
      #   - Python
      #   - Data Science
      #   - Machine Learning
      #   - AI/DL
      #   - DevOps
      #   - Cloud
      #   - Tools
      #   - Tutorials
      #   - Tips
      #   - Examples
      #   - Others
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/humblebeeintel
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/humblebeeai
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/humblebee
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/humblebeeai
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@HumbleBeeAI/videos
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/humblebeeai
copyright: Copyright &copy; 2025 Humblebee AI
