name: 2. Create Release

on:
  workflow_run:
    workflows: ["1. Bump Version"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - "v*.*.*"

jobs:
  build_publish:
    name: Create Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get latest version
        run: |
          git pull origin main
          echo "Current version: v$(./scripts/get-version.sh)"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/release.sh
