name: 3. Update Changelog

on:
  workflow_run:
    workflows: ["2. Create Release"]
    types:
      - completed
    branches:
      - main

env:
  _WORKFLOW_STATE: active

jobs:
  build_publish:
    name: Update Changelog
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/changelog.sh -c -p
      - name: Check Workflow
        run: |
          _WORKFLOW_STATE=$(gh api repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows/4.publish-docs.yml | jq -r '.state')
          echo "_WORKFLOW_STATE=${_WORKFLOW_STATE}" >> ${GITHUB_ENV}
      - name: Trigger publish docs
        if: ${{ env._WORKFLOW_STATE == 'active' }}
        run: gh workflow run 4.publish-docs.yml
